/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package resolve.lib.with.gradle;

import com.kawnayeen.HelloLib;

public class Library {
  public boolean someLibraryMethod() {
    return true;
  }

  public String sayHello() {
    var mavenLib = new HelloLib();
    return "Using --> " + mavenLib.sayHello();
  }
}
