/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package resolve.lib.with.gradle;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
  @Test
  void someLibraryMethodReturnsTrue() {
    Library classUnderTest = new Library();
    assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
  }

  @Test
  void testSayHello() {
    var lib = new Library();
    assertEquals("Using --> Java library with maven build system", lib.sayHello());
  }
}
