name: Publish package to GitHub Maven Registry
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./java-lib-with-maven
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        env:
          MAVEN_USERNAME: ${{ secrets.MVN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MVN_PASS }}
        run: mvn deploy