name: Running unit test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./java-lib-with-maven
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run unit test with maven
        run: mvn test
